### ISSUE TITLE
Skip taskbar

### ISSUE THREAD

**Issue by fabianski7** [Ximi1970/systray-x#11]
OS and architecture used: archlinux 5.6.3 64-bit
Thunderbird version and arch: 64 bit
Add-on version: 0.1.3
App version: 68.6.0
Used Qt library: default system repository

After upgrading to the latest update, thunderbird is not being hidden from the taskbar after minimizing.

[vídeo](https://upload.disroot.org/r/RtCCadPJ#+q18SjNXjocC8vUykIM84dBrYGyofP5O4bH+E8JKlJg=)

**Comment by Ximi1970** [comment]
Another distro to install... :smile: Thanks for reporting !

**Comment by Ximi1970** [comment]
Thought I would not need a dual method for skip_taskbar after tackling the Ubuntus..

**Comment by fabianski7** [comment]
that wouldn't be something managed by the DE, like gnome or plasma? regardless of the distro.

**Comment by Ximi1970** [comment]
It is handled by the window manager. The latest version uses the XSendEvent command to send the message. It is the way the command 'wmctrl' uses to control the windows.
Start TB and run:
```
wmctrl -lp
```
Find the line with Thunderbird and copy the first hex number to a save place, it is the <WinId> window id number
Use the command:
```
wmctrl -i -r <WinId> -b add,skip_taskbar
```
to make TB disappear from the taskbar.
With
```
wmctrl -i -r <WinId> -b remove,skip_taskbar
```
you can enable it again.

The 0.1.2 used a bit of a messy hack manipulating window states directly. Ubuntu 18.04 did not like that.

**Comment by fabianski7** [comment]
the `wmctrl` package is not listed as a dependency of Kwin or any plasma package. I had to install through the repository.

The commands you recommended didn't work.

**Comment by Ximi1970** [comment]
Thanks for trying. It is consistent atleast :smile:  
I will add the old hiding code in the next release. I already had prepared a dual system a few days ago in the experimental feature-taskbar_alt branch. I will clean it up and merge it into develop.
Then you have the option to choose method 1 or method 2 in the preferences.

Trying to install Arch yesterday brought back memories why I dumped it (sorry) Nicely build for your system but takes waaaay to long to install everything I normally need.Still I will try to install it in Virtualbox to find out why the wmctrl does not work. And hopefully remove the dual system again in the future.

**Comment by fabianski7** [comment]
You can install arch with the help of an installation script like archfi and archdi. Or with a pseudo distro like anarchy. Maybe that breaks the idea behind archlinux but it's quite useful in those cases.

**Comment by fabianski7** [comment]
Fixed in 0.1.4
Thanks

**Comment by duguyipiao** [comment]
For me, it is only partially fixed. When I choose method 1, clicking the tray icon works as expected, but minimizing to tray does not work. When I choose method 2, minimizing to tray works, but clicking the tray icon only minimize the window.

Manjaro XFCE, thunderbird 68.7.0

**Comment by Ximi1970** [comment]
Thanks for reporting!

**Comment by fabianski7** [comment]
Well, I guess I hadn't tested that enough.

The minimize function is working. But the option to start minimized is not.

[Check the video](https://upload.disroot.org/r/j38E1CFw#ikjW/P0KN7FvgioA7Thu+mgAZqR1JHp3qtAdBMRueEg=). After you open the thunderbird, it's visible in the taskbar.

**Comment by Ximi1970** [comment]
@fabianski7 @duguyipiao should be fixed in the develop branch, but cannot test on Arch.

**Comment by duguyipiao** [comment]
@Ximi1970 Thanks for fixing. It solved the problem of the tray icon. However, thunderbird is never shown in the task bar (I also spotted this problem sometimes in the previous version).

**Comment by fabianski7** [comment]
happens with me too

**Comment by Ximi1970** [comment]
If you want TB always visible in the taskbar, select "Default minimize" in preferences.

**Comment by fabianski7** [comment]
I don't think the systray-x workflow is well defined. I've used the webapp of tutanota email for a while and the way it works makes more sense than we are discussing it.

1. When I turned on the computer, it started minimized;
2. By clicking on the system tray icon, it shows the full interface and is available in the taskbar;
3. When you click on MINIMIZE, it was still in the taskbar like any other program; and
4. Clicking CLOSE hid it from the taskbar and remained open in the system tray. 

Systray-X already works very well on iten 1, partially on 2 and 3, and it does not work as item 4

Another extension for TB that I used before systray-x also worked like this; KMail (KDE Plasma's email client) too.

Well that's my opinion. Some people might disagree, but this is the way most applications that run in the background work.

@duguyipiao could say if you agree with this way of working

**Comment by duguyipiao** [comment]
@fabianski7 As @Ximi1970 mentioned in
https://github.com/Ximi1970/FireTray/issues/47#issuecomment-599225733
I think behavior 4 is impossible.

So I agree with 1 and 2, but I would expect 3 has the same behavior as 4:
Clicking MINIMIZE hid it from the taskbar and remained open in the system tray.

**Comment by Ximi1970** [comment]
@fabianski7 it is now impossible for a addon to intercept the close button action due to the security "improvements" of TB. Also a real minimize from startup is impossible for the same reasons. As long as TB does not provide an API to add direct access to these functions, I can not do anything except implementing workarounds.
So no actions at the moment when pressing close. It will shutdown TB.
Minimize on startup will always display a full UI  for few? seconds and as soon as the addon gets started by TB, it will minimize TB if you checked that option in the preferences.
The next round of security "improvements" made again changes in the preferences API so their recommended use for TB68 does not work anymore in TB72 an higher. Great! I can start agaiin../s

**Comment by Ximi1970** [comment]
Tested Arch and Gentoo seems to be working fine. Try the new release 0.1.5.

**Comment by duguyipiao** [comment]
@Ximi1970 Works for me. Thanks for fixing.

**Comment by fabianski7** [comment]
working here too. thanks!

**Comment by PS1Online** [comment]
> @fabianski7 @duguyipiao should be fixed in the develop branch, but cannot test on Arch.

Today, with the latest version of Thunderbird, the latest version of Ubuntu, the latest version of Birdtray and the latest version of SysTray-X the problem is still present: "The minimize function is working. But the option to start minimized is not.".
