### ISSUE TITLE
New release 0.9.9 does not work with TB 121 and older

### ISSUE THREAD

**Issue by Ximi1970** [Ximi1970/systray-x#187]
**Describe the bug**
New filters do not work with older TBs when API count is selected.

**To Reproduce**
Install new version

**Expected behavior**
Mails should be counted according to the filter setup

**Screenshots**

**Desktop (please complete the following information):**
 - OS / distribution: openSuse Leap 15.5
 - Architecture 64bit
 - Desktop type / Window Manager: KDE
 - Thunderbird version and arch 115.x 64
 - Thunderbird package type: system
 - Run `echo $XDG_SESSION_TYPE`  x11
 - Add-on version 0.9.9
 - App version 0.9.9
 - Install type:  local build  
 - Used Qt library default system repository

**Comment by Ximi1970** [comment]
Fixed.

**Comment by Cherkah** [comment]
hi, but the bug is still there:
Mails are not counted/showed even if the filter was setted up

Operating System: EndeavourOS 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.8-arch1-1 (64-bit)
Graphics Platform: Wayland

thunderbird: 115.10.1 (64 bits)

name: systray-x-kde
Version: 0.9.9-1

**Comment by Ximi1970** [comment]
systray-x-kde is no package of mine?

**Comment by Cherkah** [comment]
ok so i removed it & replaced it with systray-x-common (repos extra/).
but the issue remains

**Comment by Ximi1970** [comment]
Also not a package of mine? Please fill in the standard bug report form:

https://github.com/Ximi1970/systray-x/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=
